/** 卓タブレット（お客様）向け UI 文言。厨房・伝票用の品名は日本語のまま別経路で送る。 */
import { OVERLAY_EN, OVERLAY_JA } from './guestUiStringsOverlays.js';

const JA = {
  lang_action_en: 'English',
  lang_action_ja: '日本語',
  nav_label: 'メニューカテゴリ',
  nav_food: 'フード',
  nav_aburasoba: '油そば',
  nav_sidedish: 'サイドメニュー',
  nav_drinks: 'お飲み物',
  nav_nomihodai: '飲み放題',
  nav_drink: 'ドリンク一覧',
  nav_shochu: 'おすすめ①',
  nav_dessert: 'デザート・お持ち帰り',
  nav_fruit: 'ソフトクリーム',
  nav_cafe: 'カフェドリンク',
  nav_takeout: 'テイクアウト\nスイーツ',
  btn_checkout: 'お会計する',
  btn_current_bill: '現在のお会計',
  cart_title: 'ご注文内容',
  cart_clear: '🗑️ すべて削除',
  cart_close: 'カートを閉じる',
  cart_edge: 'カート',
  cart_total: '合計',
  cart_tax: '（税込）',
  cart_confirm: '注文を確定する ＞',
  cart_empty: 'カートに商品がありません。',
  sd_cart_add_to: 'カートに追加',
  takeout_cart_add: '＋ カートに追加',
  bill_checkout: 'お会計する',
  bill_title: '現在のお会計',
  bill_close: '閉じる',
  bill_split: '人数割り勘',
  bill_split_people: '人数',
  bill_split_per: '1人あたり',
  bill_people_unit: '人',
  bottom_alcohol:
    '卓チャージは店舗の判断で加算する場合があります（税込）。金額はスタッフが設定します。',
  guest_aria_checkout_farewell: '会計完了のご案内',
  guest_aria_checkout_thanks: 'お会計を承りました',
  drink_lock_before: '飲み放題適用中は、ご注文は',
  drink_lock_tab: '「飲み放題」タブ',
  drink_lock_after: 'からお選びください（この一覧は閲覧のみです）。',
  drink_lock_title: '飲み放題タブからご注文ください',
  drink_page_sub: '混雑時は2時間を目途にお席をお譲り頂く場合がございます。',
  drink_row_na_title: '店頭でご確認ください',
  drink_add: '追加',
  item_add_plus: '＋ 追加',
  drink_footer: '※価格はすべて税込です。',
  shochu_page_alt: '焼酎メニュー',
  shochu_tap_hint: '瓶やおつまみの写真をタップするとカートに追加できます。',
  shochu_hotspot_aria: '{name}を注文',
  shochu_added: '{name}をカートに追加しました',
  shochu_link_drink_list: 'すべてのドリンクはドリンク一覧へ →',
  shochu_image_missing: '焼酎メニュー画像が見つかりません。次のファイルを public フォルダに配置してください。',
  notice_no_items: '注文する商品がありません。',
  notice_order_ok: 'ご注文を受け付けました（{count}点）。',
  notice_checkout_zero: '現在のお会計は0円です。',
  notice_checkout_no_table: '卓番号が設定されていません。URL の ?table= を確認するか、スタッフにお知らせください。',
  party_gate_title: 'ご来店の人数',
  party_gate_lead: '注文の前に、男性・女性・お子様の人数を教えてください。',
  party_gate_table: '卓 {table}',
  party_gate_table_short: '卓',
  party_gate_submit_short: 'はじめる',
  party_gate_need_short: '1名以上',
  party_gate_fail_short: '送信できません',
  onboarding_back_short: '戻る',
  party_gate_men: '男性',
  party_gate_women: '女性',
  party_gate_children: 'お子様',
  party_gate_total: '合計 {n} 名',
  party_gate_submit: '注文をはじめる',
  party_gate_submitting: '送信中…',
  party_gate_need_one: '合計1名以上で入力してください。',
  party_gate_fail: '送信できませんでした。通信を確認するか、スタッフにお知らせください。',
  onboarding_locale_title: 'ご利用の言語',
  onboarding_locale_lead: '画面の言語を選んでください（統計用）。次に人数の入力へ進みます。',
  onboarding_locale_ja: '日本語',
  onboarding_locale_ja_sub: '日本人（統計）',
  onboarding_locale_en: 'English',
  onboarding_locale_en_sub: '外国人（統計）',
  onboarding_locale_ja_short: '日本',
  onboarding_locale_en_short: '外国',
  onboarding_locale_ja_aria: '日本人',
  onboarding_locale_en_aria: '外国人',
  onboarding_back_locale: '言語を選び直す',
  notice_checkout_ok: 'お会計のご依頼を受け付けました。スタッフが伺います。',
  notice_order_fail_prefix: '注文を送れませんでした。',
  notice_checkout_fail_prefix: 'お会計依頼を送信できませんでした。',
  notice_checkout_fail_suffix: '通信を確認してください。',
  notice_stock_short: 'テイクアウトスイーツの在庫が足りません（{id}: 残り {have}、ご希望 {need}）。カートを調整してください。',
  tax_included_short: '（税込）',
  cafe_tax_note: '（税込）',
  header_aburasoba: '米風亭 油そば',
  header_sidedish: 'サイドメニュー',
  header_fruit: 'ソフトクリーム',
  header_takeout: 'takeout北海道スイーツ',
  sd_page_foot: '※表示価格はすべて税込です。',
  nh_banner_active: '飲み放題中',
  nh_banner_extend_soon: 'まもなく自動延長のタイミングです',
  nh_banner_until_end: '終了まで {m} 分',
  nh_banner_until_extend: '自動延長まで あと {m} 分',
  nh_banner_until_lo: 'ご利用枠終了（自動延長）まで {m} 分',
  nh_banner_checkout_sync: 'お会計のご依頼を厨房へ連携中です',
  nh_banner_checkout_ok_title: 'お会計のご依頼を承りました',
  nh_banner_checkout_ok_body: '厨房へ連携しています。少々お待ちください',
  nh_prospect_title: '飲み放題',
  nh_prospect_time_aria: '{base}分',
  nh_prospect_time_unit: '分',
  nh_prospect_plan: '料金',
  nh_prospect_tax: '税込',
  nh_prospect_female: '女性',
  nh_prospect_male: '男性',
  nh_prospect_auto_title: '自動延長',
  nh_prospect_extend_min_unit: '分',
  nh_prospect_cta_aria: '飲み放題を希望する',
  nh_prospect_cta: '希望する',
  nh_prospect_terms_title: 'ご利用条件',
  nh_prospect_terms_1: 'グループ単位で同一ご注文',
  nh_prospect_terms_2: '店員からのコールはありません。タブレット内の時間をご確認ください。',
  nh_prospect_terms_3: 'タクシーの手配はお早めに。お会計後はお席のご協力お願い致します。',
  nh_prospect_menu_label: 'MENU',
  nh_prospect_menu_empty: 'メニュー準備中',
  nh_wait_title: '確認中',
  nh_wait_table_unit: '番卓',
  nh_wait_cancel: '取り消す',
  nh_checkout_bussing: 'バッシングOK',
  nh_checkout_bussing_busy: '…',
  nh_checkout_bussing_aria_busy: '処理中',
  nh_checkout_bussing_aria: 'バッシングOK。卓タブレットを次のお客様用に戻す',
  nh_checkout_alert_fail: '送信に失敗しました。通信を確認してください。',
  nh_checkout_farewell_coop: '次のお客様ご案内準備のため',
  nh_checkout_farewell_seat: 'お席のご協力お願いいたします',
  nh_checkout_ty_headline: 'FREE FLOWは終了しました。',
  nh_checkout_ty_headline_standard: 'お会計のご依頼をお受けしました。',
  nh_checkout_ty_p1: 'お会計を承りました。',
  nh_checkout_ty_p2: 'スタッフがお席まで伺います。',
  nh_drink_order: '注文',
  nh_drink_bar_aria: 'セッションステータス',
  nh_drink_remain: 'ご利用残り時間',
  nh_drink_extend_until: '次回自動延長まで',
  nh_drink_extend_system: '自動延長システム',
  nh_drink_extend_min: '{n}分',
  nh_drink_extend_tax: '（税込）',
  nh_drink_extend_cap: '延長1回あたり · 男女共通',
  nh_drink_checkout: 'お会計する',
  nh_drink_send_fail: '送信に失敗しました',
  nh_drink_queue_full: '提供後に次のご注文が可能です（未提供：{p}／{people}）',
  nh_drink_queue_short: '未提供：{p}／{people}',
  nh_drink_menu_title: '飲み放題メニュー',
  nh_drink_add_cart: 'カートへ',
  nh_drink_menu_foot: '※飲み残しは別途料金をいただく場合がございます。',
  nh_drink_cart_title: '注文カート',
  nh_drink_cart_empty: 'メニューの「注文」でここに追加されます',
  nh_drink_remove_aria: '{name}をカートから削除',
  nh_drink_send: '送信',
  nh_drink_send_wait: '未提供が人数分あるため、送信は提供後までお待ちください。',
  nh_drink_cart_foot: '送信後はキッチンへ通知され、こちらから変更できません。',
  nh_drink_refill: 'おかわり',
  nh_drink_hub_title: 'ご注文状況',
  nh_drink_hub_hint_served: '※提供済にすると次のご注文が可能になります',
  nh_drink_hub_hint_kitchen: '※厨房での提供状況です',
  nh_drink_hub_pending: '未提供ドリンク {n} 杯',
  nh_drink_hub_people: '（ご利用人数：{n}名）',
  nh_drink_hub_male_title: '男性{m}',
  nh_drink_hub_female_title: '女性{f}',
  nh_drink_hub_more: 'あと{n}杯ご提供で次のご注文が可能になります',
  nh_drink_hub_ready: '未提供のドリンクはありません。追加注文が可能です。',
  nh_drink_hub_none: '未提供のドリンクはありません。',
  nh_drink_hub_no_orders: 'まだ注文がありません',
  nh_drink_status_served: '提供済',
  nh_drink_status_pending: '注文中',
  nh_drink_glass_note: 'グラス交換制です。空いたグラスをお渡しください。',
  nh_auto_extend_line1: '{base}分',
  nh_auto_extend_line2: '自動延長',
  nh_auto_extend_line3: 'プラン',
  abu_flow_hint:
    '「追加」からサイズとトッピングをまとめて選べます。下のトッピング一覧からはトッピングのみ追加できます。',
  abu_toppings_header: 'トッピングで自分好みに',
  abu_toppings_tax: '※価格はすべて税込みです。',
  abu_flow_pick_size: 'サイズを選んでください',
  abu_flow_next_toppings: '次へ（トッピング）',
  abu_flow_pick_toppings: 'トッピングはいかがですか？',
  abu_flow_topping_note: '複数選べます（タップで追加・解除）※税込',
  abu_flow_back: '戻る',
  abu_cart_to_cart: 'カートに追加',
  abu_flow_extra_line: '＋トッピング … ￥{price}',
  abu_flow_total_line: '計 ￥{total}（税込）',
  abu_add: '追加',
  abu_hero_cart: 'カートに追加',
  ...OVERLAY_JA,
};

const EN = {
  lang_action_en: 'English',
  lang_action_ja: '日本語',
  nav_label: 'Menu categories',
  nav_food: 'Food',
  nav_aburasoba: 'Aburasoba',
  nav_sidedish: 'Side dishes',
  nav_drinks: 'Drinks',
  nav_nomihodai: 'Free flow',
  nav_drink: 'Drinks list',
  nav_shochu: 'Recommend ①',
  nav_dessert: 'Dessert & to-go',
  nav_fruit: 'Soft serve',
  nav_cafe: 'Cafe drinks',
  nav_takeout: 'Takeout\nsweets',
  btn_checkout: 'Request check',
  btn_current_bill: 'Current bill',
  cart_title: 'Your order',
  cart_clear: '🗑️ Clear all',
  cart_close: 'Close cart',
  cart_edge: 'Cart',
  cart_total: 'Total',
  cart_tax: '(incl. tax)',
  cart_confirm: 'Place order ＞',
  cart_empty: 'Your cart is empty.',
  sd_cart_add_to: 'Add to cart',
  takeout_cart_add: '＋ Add to cart',
  bill_checkout: 'Request check',
  bill_title: 'Current bill',
  bill_close: 'Close',
  bill_split: 'Split bill',
  bill_split_people: 'Guests',
  bill_split_per: 'Per person',
  bill_people_unit: ' guests',
  bottom_alcohol:
    'A table cover charge may be added at the restaurant’s discretion (incl. tax). Staff set the amount.',
  guest_aria_checkout_farewell: 'After payment',
  guest_aria_checkout_thanks: 'Check request received',
  drink_lock_before: 'During free flow, order from the ',
  drink_lock_tab: 'Free flow',
  drink_lock_after: ' tab (this list is view-only).',
  drink_lock_title: 'Order from the Free flow tab',
  drink_page_sub: 'At busy times we may ask you to give up your seat after about 2 hours.',
  drink_row_na_title: 'Ask staff for price',
  drink_add: 'Add',
  item_add_plus: '＋ Add',
  drink_footer: 'All prices include tax.',
  shochu_page_alt: 'Shochu menu',
  shochu_tap_hint: 'Tap a bottle or snack photo to add it to your cart.',
  shochu_hotspot_aria: 'Order {name}',
  shochu_added: 'Added {name} to cart',
  shochu_link_drink_list: 'See all drinks in the drinks list →',
  shochu_image_missing: 'Shochu menu image not found. Place the file in the public folder:',
  notice_no_items: 'There are no items to order.',
  notice_order_ok: 'Your order was received ({count} items).',
  notice_checkout_zero: 'The current bill is ¥0.',
  notice_checkout_no_table: 'Table number is not set. Check the ?table= URL parameter or ask staff.',
  party_gate_title: 'Party size',
  party_gate_lead: 'Before ordering, please tell us how many men, women, and children are at your table.',
  party_gate_table: 'Table {table}',
  party_gate_table_short: 'Table',
  party_gate_submit_short: 'Start',
  party_gate_need_short: 'At least 1',
  party_gate_fail_short: 'Could not save',
  onboarding_back_short: 'Back',
  party_gate_men: 'Men',
  party_gate_women: 'Women',
  party_gate_children: 'Children',
  party_gate_total: 'Total: {n}',
  party_gate_submit: 'Start ordering',
  party_gate_submitting: 'Sending…',
  party_gate_need_one: 'Please enter at least 1 guest.',
  party_gate_fail: 'Could not save. Check your connection or ask staff.',
  onboarding_locale_title: 'Choose your language',
  onboarding_locale_lead: 'Select a language for the screen (for statistics). Next, enter your party size.',
  onboarding_locale_ja: 'Japanese',
  onboarding_locale_ja_sub: 'Japanese (stats)',
  onboarding_locale_en: 'English',
  onboarding_locale_en_sub: 'Non-Japanese (stats)',
  onboarding_locale_ja_short: 'Japan',
  onboarding_locale_en_short: 'Other',
  onboarding_locale_ja_aria: 'Japanese guest',
  onboarding_locale_en_aria: 'Non-Japanese guest',
  onboarding_back_locale: 'Change language',
  notice_checkout_ok: 'We received your check request. A staff member will come to your table.',
  notice_order_fail_prefix: 'Could not send your order.',
  notice_checkout_fail_prefix: 'Could not send your check request.',
  notice_checkout_fail_suffix: 'Please check your connection.',
  notice_stock_short:
    'Not enough takeout sweets stock ({id}: {have} left, you asked {need}). Please adjust your cart.',
  tax_included_short: '(incl. tax)',
  cafe_tax_note: '(incl. tax)',
  header_aburasoba: 'Beifutei aburasoba',
  header_sidedish: 'Side menu',
  header_fruit: 'Soft serve',
  header_takeout: 'Hokkaido takeout sweets',
  sd_page_foot: 'All prices include tax.',
  nh_banner_active: 'Free flow',
  nh_banner_extend_soon: 'Auto-extension window is coming up',
  nh_banner_until_end: '{m} min until session end',
  nh_banner_until_extend: '{m} min until auto-extension',
  nh_banner_until_lo: '{m} min until last orders (before extension)',
  nh_banner_checkout_sync: 'Sending your check request to the kitchen',
  nh_banner_checkout_ok_title: 'Check request received',
  nh_banner_checkout_ok_body: 'Sent to the kitchen. Please wait a moment.',
  nh_prospect_title: 'Free flow',
  nh_prospect_time_aria: '{base} minutes',
  nh_prospect_time_unit: 'min',
  nh_prospect_plan: 'Prices',
  nh_prospect_tax: 'incl. tax',
  nh_prospect_female: 'Women',
  nh_prospect_male: 'Men',
  nh_prospect_auto_title: 'Auto-extend',
  nh_prospect_extend_min_unit: ' min',
  nh_prospect_cta_aria: 'Request free flow',
  nh_prospect_cta: 'Request',
  nh_prospect_terms_title: 'Rules',
  nh_prospect_terms_1: 'One order per group',
  nh_prospect_terms_2: 'No staff time call — check the timer on this tablet.',
  nh_prospect_terms_3: 'Arrange taxis early. Please help reset the table after checkout.',
  nh_prospect_menu_label: 'MENU',
  nh_prospect_menu_empty: 'Menu loading',
  nh_wait_title: 'Confirming',
  nh_wait_table_unit: 'Table',
  nh_wait_cancel: 'Cancel',
  nh_checkout_bussing: 'Table cleared',
  nh_checkout_bussing_busy: '…',
  nh_checkout_bussing_aria_busy: 'Working',
  nh_checkout_bussing_aria: 'Table cleared — reset tablet for the next guests',
  nh_checkout_alert_fail: 'Could not send. Please check your connection.',
  nh_checkout_farewell_coop: 'To welcome the next guests',
  nh_checkout_farewell_seat: 'we appreciate your help leaving the table',
  nh_checkout_ty_headline: 'Free flow has ended.',
  nh_checkout_ty_headline_standard: "We've received your check request.",
  nh_checkout_ty_p1: 'We have started your check.',
  nh_checkout_ty_p2: 'A staff member will come to your table.',
  nh_drink_order: 'Order',
  nh_drink_bar_aria: 'Session status',
  nh_drink_remain: 'Time remaining',
  nh_drink_extend_until: 'Until next auto-extension',
  nh_drink_extend_system: 'Auto-extension',
  nh_drink_extend_min: '{n} min',
  nh_drink_extend_tax: '(incl. tax)',
  nh_drink_extend_cap: 'Per extension · same for all',
  nh_drink_checkout: 'Request check',
  nh_drink_send_fail: 'Could not send',
  nh_drink_queue_full: 'Next order after drinks are served (pending: {p} / {people})',
  nh_drink_queue_short: 'Pending: {p} / {people}',
  nh_drink_menu_title: 'Free flow menu',
  nh_drink_add_cart: 'Add to cart',
  nh_drink_menu_foot: 'Leftover drinks may incur extra charges.',
  nh_drink_cart_title: 'Order cart',
  nh_drink_cart_empty: 'Tap “Order” on the menu to add items here',
  nh_drink_remove_aria: 'Remove {name} from cart',
  nh_drink_send: 'Send',
  nh_drink_send_wait: 'You have the maximum pending drinks per guest; please wait until served.',
  nh_drink_cart_foot: 'After sending, the kitchen is notified and you cannot change it here.',
  nh_drink_refill: 'Another round',
  nh_drink_hub_title: 'Order status',
  nh_drink_hub_hint_served: '※ After “served”, you can place your next order',
  nh_drink_hub_hint_kitchen: '※ Status as updated by the kitchen',
  nh_drink_hub_pending: 'Pending drinks: {n}',
  nh_drink_hub_people: '(party size: {n})',
  nh_drink_hub_male_title: 'Men: {m}',
  nh_drink_hub_female_title: 'Women: {f}',
  nh_drink_hub_more: '{n} more drink(s) until you can order again',
  nh_drink_hub_ready: 'No pending drinks. You can add more orders.',
  nh_drink_hub_none: 'No pending drinks.',
  nh_drink_hub_no_orders: 'No orders yet',
  nh_drink_status_served: 'Served',
  nh_drink_status_pending: 'Pending',
  nh_drink_glass_note: 'Glass exchange: please return empty glasses when ordering.',
  nh_auto_extend_line1: '{base} min',
  nh_auto_extend_line2: 'Auto',
  nh_auto_extend_line3: 'plan',
  abu_flow_hint:
    'Use “Add” to choose size and toppings together. From the topping list below you can add toppings only.',
  abu_toppings_header: 'Customize with toppings',
  abu_toppings_tax: '※All prices include tax.',
  abu_flow_pick_size: 'Choose a size',
  abu_flow_next_toppings: 'Next (toppings)',
  abu_flow_pick_toppings: 'Would you like toppings?',
  abu_flow_topping_note: 'You can pick multiple (tap to add/remove). Prices include tax.',
  abu_flow_back: 'Back',
  abu_cart_to_cart: 'Add to cart',
  abu_flow_extra_line: '+ Toppings … ¥{price}',
  abu_flow_total_line: 'Total ¥{total} (incl. tax)',
  abu_add: 'Add',
  abu_hero_cart: 'Add to cart',
  ...OVERLAY_EN,
};

const PACKS = { ja: JA, en: EN };

/**
 * @param {'ja' | 'en'} locale
 * @param {keyof typeof JA} key
 * @param {Record<string, string | number>} [vars]
 */
export function guestUiT(locale, key, vars) {
  const pack = PACKS[locale] || JA;
  let s = pack[key] ?? JA[key];
  if (s == null) return String(key);
  if (vars && typeof s === 'string') {
    s = s.replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : ''));
  }
  return s;
}
