/** guestUiStrings.js にマージする追加キー（卓タブレット英語化用） */

export const OVERLAY_JA = {
  abu_size_s: '小',
  abu_size_m: '並',
  abu_size_l: '大',
  abu_bowl_normal: '米風亭 油そば',
  abu_bowl_spicy: '辛々担々 油そば',
  abu_bowl_cheese: 'チーズ 油そば',
  /** 旧カート行のみ（メニューからは削除済み） */
  abu_bowl_negi: 'ネギ盛り 油そば',
  abu_hero_subtitle: '昭和の味を受け継ぐ、',
  abu_hero_subtitle_em: '元祖',
  abu_hero_subtitle_after: ' 油そば。',
  abu_hero_title1: '米風亭',
  abu_hero_title2: '油そば',
  abu_hero_tag: '— シンプル、だけど奥深い。—',
  abu_badge_pop1: '人気',
  abu_badge_pop2: 'No.1',
  abu_right_title: '札幌米風亭 油そば',
  abu_right_desc: '特製ダレがもちもちの麺に絡む、\n飽きのこない一杯。\n毎日でも食べたくなる一杯',
  abu_section_other: '別仕立て',
  abu_rec_spicy_title: '辛々担々 油そば',
  abu_rec_spicy_desc: '肉みその旨味広がる\nやみつき坦々油そば\n花椒はお好みで',
  abu_rec_cheese_title: 'チーズ 油そば',
  abu_rec_cheese_desc: 'チーズ好き必見\nたっぷりチーズを炙って提供',
  nh_empty_beer: 'マスターで「ビール」「BEER」を含むカテゴリを追加すると表示されます。',
  nh_empty_highball: 'マスターで「ハイボール」「HIGHBALL」を含むカテゴリを追加すると表示されます。',
  nh_empty_shochu: 'マスターで「焼酎」「SHOCHU」を含むカテゴリを追加すると表示されます。',
  nh_empty_cocktail:
    'マスターで「カクテル」「チューハイ」「サワー」「ジントニック」等を含むカテゴリを追加すると表示されます。',
  nh_empty_wine: 'マスターで「ワイン」「WINE」を含むカテゴリを追加すると表示されます。',
  nh_empty_soft: 'マスターで「ソフト」「ジュース」「ウーロン」等を含むカテゴリを追加すると表示されます。',
  nh_cart_plan_mf: '飲み放題プラン（男性{m}・女性{f}）',
  nh_cart_plan_n: '飲み放題プラン（{n}名）',
  drink_price_ask: 'ASK',
  sd_feature_l1: '生BIG',
  sd_feature_l2: 'フランク3種盛り',
  sd_feature_desc: 'お酒に合う“間違いない”一皿',
  sd_yen_tax: '円',
  sd_recommend_aria: 'おすすめのお酒',
  sd_recommend_title: 'おすすめのお酒',
  sd_section_toriaezu: 'とりあえず',
  sd_section_popular: 'みんな大好き',
  sd_section_drink_snack: '呑ませる一皿',
  pizza_coming_note: '※6月下旬より週末のみ',
  pizza_takeout_foot: '※ 全品テイクアウト可（容器代100円）',
  cafe_coffee_title: 'コーヒー',
  cafe_coffee_desc: 'グァテマラ産・中深煎りの豆。\nホット・アイスご用意しています。',
  cafe_latte_title: 'カフェラテ',
  cafe_latte_desc: 'エスプレッソに、\n北海道産ジャージーミルク。',
  cafe_straw_title: '生いちごミルク',
  cafe_straw_desc: '自家製いちごソースと、\nリッチな苺みるく。',
  cafe_choco_title: 'ラテチョコラータ',
  cafe_choco_desc: '濃厚チョコソースと、\n北海道産ジャージーミルク。',
  cafe_sub_coffee: 'Coffee',
  cafe_sub_latte: 'Cafe Latte',
  cafe_sub_straw: 'Fresh Strawberry Milk',
  cafe_sub_choco: 'Latte Chocolata',
  cafe_cart_coffee: 'コーヒー（{temp}/{size}）',
  cafe_cart_latte: 'カフェラテ（{temp}/{size}）',
  cafe_cart_strawberry: '生いちごミルク（{size}）',
  cafe_cart_chocolata: 'ラテチョコラータ（{size}）',
  fruit_ribbon_red: '新鮮 フルーツを贅沢に！',
  fruit_hero_lead: 'フレッシュフルーツソフト',
  fruit_hero_title: '本日のソフトクリーム',
  fruit_hero_desc: '新鮮フルーツの上に\nジェラ生ソフトを乗せました',
  fruit_hero_tagline: 'ミニ or レギュラー',
  fruit_hero_note: 'ご提供できるフルーツは日替わりです。',
  fruit_size_mini: 'ミニ',
  fruit_size_regular: 'レギュラー',
  fruit_cart_soft: '本日のソフトクリーム ({size})',
  fruit_ribbon_tokachi: '北海道十勝ミルク使用',
  fruit_gelato_title: 'ジェラ生ソフト',
  fruit_gelato_sub: 'Gelato Soft',
  fruit_gelato_desc: '北海道産十勝ミルクを原料とした\nふわもこ自家製ソフトクリーム',
  fruit_gelato_price_line: 'カップ or コーン\n460yen',
  fruit_soft_cone: 'コーン',
  fruit_soft_cup: 'カップ',
  fruit_cart_gelato: 'ジェラ生ソフト ({type})',
  fruit_affogato_title: 'アフォガード',
  fruit_affogato_sub: 'Affogato',
  fruit_affogato_desc: 'ジェラ生ソフトに\nほろ苦いエスプレッソを注ぎます',
  fruit_affogato_price_line: '680yen',
  fruit_hero_price_between: 'yen / ',
  fruit_hero_price_suffix: 'yen',
  fruit_yen_suffix: 'yen〜',
  ts_header_note: '※油そば・フードメニュー・お酒のご利用の方は食中後のデザートとしてご利用いただけます',
  ts_section_furusan: 'フルーツサンド',
  ts_section_kukki: 'クッキーサンド',
  ts_section_scone: 'スコーン',
  ts_section_rittire: 'リッチレアクッキー',
  ts_soldout: '品切れ',
  ts_popular_no: '人気',
  ts_rank_suffix: 'No.',
  ts_view_all: 'すべての商品を見る ∨',
  ts_soldout_title: '品切れのため注文できません',
  price_yen_unit: '円',
  sd_name_frank: '生BIG\nフランク3種盛り',
  sd_name_beer: 'グラス生ビール（一番搾り）',
  sd_name_highball: 'ハイボール',
  sd_name_lemon_sour: 'レモンサワー',
  sd_name_pickles: '自家製ピクルス盛り',
  sd_name_edamame: '塩ゆで枝豆',
  sd_name_wiener: '赤ウインナー',
  sd_name_potato_label: 'ポテト',
  sd_name_potato_cart: 'シューストポテト',
  sd_name_nugget_label: 'チキンナゲット (5ヶ)',
  sd_name_nugget_cart: 'チキンナゲット',
  sd_name_hash_label: 'ひと口ハッシュドポテト (5ヶ)',
  sd_name_hash_cart: 'ひと口ハッシュドポテト',
  sd_name_jerky_label: '自家製牛タンジャーキー',
  sd_name_jerky_cart: '牛タンジャーキー',
  sd_name_karaage: 'Yum特性から揚げ',
  sd_name_uzura_label: 'うずら味玉（5粒）',
  sd_name_chashu_label: 'おつまみチャーシュー',
};

export const OVERLAY_EN = {
  abu_size_s: 'S',
  abu_size_m: 'M',
  abu_size_l: 'L',
  abu_bowl_normal: 'Beifutei aburasoba',
  abu_bowl_spicy: 'Spicy tantan aburasoba',
  abu_bowl_cheese: 'Cheese aburasoba',
  /** Legacy cart lines only */
  abu_bowl_negi: 'Negi-mori aburasoba',
  abu_hero_subtitle: 'Carrying on the taste of Showa — the ',
  abu_hero_subtitle_em: 'original',
  abu_hero_subtitle_after: ' oil noodles.',
  abu_hero_title1: 'Beifutei',
  abu_hero_title2: 'Aburasoba',
  abu_hero_tag: '— Simple, yet deep.',
  abu_badge_pop1: 'Popular',
  abu_badge_pop2: 'No.1',
  abu_right_title: 'Sapporo Beifutei aburasoba',
  abu_right_desc:
    'Our special sauce clings to chewy noodles —\na bowl you never tire of,\none you will want again tomorrow.',
  abu_section_other: 'Other styles',
  abu_rec_spicy_title: 'Spicy tantan aburasoba',
  abu_rec_spicy_desc: 'Rich miso meat flavor —\naddictive tantan oil noodles.\nSichuan pepper to taste.',
  abu_rec_cheese_title: 'Cheese aburasoba',
  abu_rec_cheese_desc: 'For cheese lovers —\nplenty of cheese, torched to serve.',
  nh_empty_beer: 'Add a category containing “beer” or “BEER” in Master to show items here.',
  nh_empty_highball: 'Add a category containing “highball” or “HIGHBALL” in Master to show items here.',
  nh_empty_shochu: 'Add a category containing “shochu” or “SHOCHU” in Master to show items here.',
  nh_empty_cocktail:
    'Add a category containing “cocktail”, “chu-hi”, “sour”, “gin and tonic”, etc. in Master to show items here.',
  nh_empty_wine: 'Add a category containing “wine” or “WINE” in Master to show items here.',
  nh_empty_soft: 'Add a category containing “soft”, “juice”, “oolong”, etc. in Master to show items here.',
  nh_cart_plan_mf: 'Free-flow plan (men {m}, women {f})',
  nh_cart_plan_n: 'Free-flow plan ({n} guests)',
  drink_price_ask: 'ASK',
  sd_feature_l1: 'BIG raw',
  sd_feature_l2: '3-sausage platter',
  sd_feature_desc: 'A safe bet plate with drinks.',
  sd_yen_tax: 'yen',
  sd_recommend_aria: 'Recommended drinks',
  sd_recommend_title: 'Recommended drinks',
  sd_section_toriaezu: 'To start',
  sd_section_popular: 'Crowd favorites',
  sd_section_drink_snack: 'Great with drinks',
  pizza_coming_note: '※ From late June, weekends only',
  pizza_takeout_foot: '※ All items available to go (+¥100 container)',
  cafe_coffee_title: 'Coffee',
  cafe_coffee_desc: 'Guatemala beans, medium-dark roast.\nHot or iced.',
  cafe_latte_title: 'Cafe latte',
  cafe_latte_desc: 'Espresso with\nHokkaido Jersey milk.',
  cafe_straw_title: 'Fresh strawberry milk',
  cafe_straw_desc: 'House strawberry sauce and\nrich strawberry milk.',
  cafe_choco_title: 'Latte chocolata',
  cafe_choco_desc: 'Rich chocolate sauce with\nHokkaido Jersey milk.',
  cafe_sub_coffee: 'コーヒー',
  cafe_sub_latte: 'カフェラテ',
  cafe_sub_straw: '生いちごミルク',
  cafe_sub_choco: 'ラテチョコラータ',
  cafe_cart_coffee: 'Coffee ({temp}/{size})',
  cafe_cart_latte: 'Cafe latte ({temp}/{size})',
  cafe_cart_strawberry: 'Fresh strawberry milk ({size})',
  cafe_cart_chocolata: 'Latte chocolata ({size})',
  fruit_ribbon_red: 'Fresh fruit, generous style',
  fruit_hero_lead: 'Fresh fruit soft serve',
  fruit_hero_title: "Today's fruit soft serve",
  fruit_hero_desc: 'Gelato soft serve\non fresh seasonal fruit.',
  fruit_hero_tagline: 'Mini or regular',
  fruit_hero_note: 'Fruit selection changes daily.',
  fruit_size_mini: 'Mini',
  fruit_size_regular: 'Regular',
  fruit_cart_soft: "Today's fruit soft serve ({size})",
  fruit_ribbon_tokachi: 'Tokachi, Hokkaido milk',
  fruit_gelato_title: 'Gelato soft serve',
  fruit_gelato_sub: 'ジェラ生ソフト',
  fruit_gelato_desc: 'Fluffy house soft serve\nmade with Tokachi milk from Hokkaido.',
  fruit_gelato_price_line: 'Cup or cone\n¥460',
  fruit_soft_cone: 'Cone',
  fruit_soft_cup: 'Cup',
  fruit_cart_gelato: 'Gelato soft serve ({type})',
  fruit_affogato_title: 'Affogato',
  fruit_affogato_sub: 'アフォガード',
  fruit_affogato_desc: 'Gelato soft serve\nwith bittersweet espresso poured over.',
  fruit_affogato_price_line: '¥680~',
  fruit_hero_price_between: ' / ',
  fruit_hero_price_suffix: ' yen',
  fruit_yen_suffix: 'yen〜',
  ts_header_note:
    '※ If you are ordering aburasoba, food, or alcohol, enjoy these sweets after your meal.',
  ts_section_furusan: 'Fruit sandwich',
  ts_section_kukki: 'Cookie sandwich',
  ts_section_scone: 'Scone',
  ts_section_rittire: 'Little rare cookie',
  ts_soldout: 'Sold out',
  ts_popular_no: 'Popular',
  ts_rank_suffix: 'No.',
  ts_view_all: 'View all items ∨',
  ts_soldout_title: 'Sold out — cannot add to cart',
  price_yen_unit: 'yen',
  sd_name_frank: 'BIG raw\n3-sausage platter',
  sd_name_beer: 'Draft beer (Kirin Ichiban, glass)',
  sd_name_highball: 'Highball',
  sd_name_lemon_sour: 'Lemon sour',
  sd_name_pickles: 'House pickle platter',
  sd_name_edamame: 'Salted edamame',
  sd_name_wiener: 'Red wiener sausage',
  sd_name_potato_label: 'Potatoes',
  sd_name_potato_cart: 'Choucroute-style potatoes',
  sd_name_nugget_label: 'Chicken nuggets (5 pcs)',
  sd_name_nugget_cart: 'Chicken nuggets',
  sd_name_hash_label: 'Mini hash browns (5 pcs)',
  sd_name_hash_cart: 'Mini hash browns',
  sd_name_jerky_label: 'House beef tongue jerky',
  sd_name_jerky_cart: 'Beef tongue jerky',
  sd_name_karaage: 'Yum-style karaage',
  sd_name_uzura_label: 'Seasoned quail eggs (5)',
  sd_name_chashu_label: 'Snack chashu pork',
};
